# -*- rpm-spec -*-
BuildRoot:      /opt/opendlv.carolocup.build/code-prefix/src/code-build/_CPack_Packages/Linux/RPM/carolocup-software_0.0.2_x86_64/carolocup-software
Summary:        carolocup-software contains the software for CaroloCup realized with OpenDLV and OpenDaVINCI.
Name:           carolocup-software-carolocup-software
Version:        0.0.2
Release:        1
License:        GPL
Group:          unknown
Vendor:         Christian Berger

Requires: opendavinci-lib











Prefix: /usr


%define _rpmdir /opt/opendlv.carolocup.build/code-prefix/src/code-build/_CPack_Packages/Linux/RPM
%define _rpmfilename carolocup-software_0.0.2_x86_64-carolocup-software.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /opt/opendlv.carolocup.build/code-prefix/src/code-build/_CPack_Packages/Linux/RPM




%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/opt/opendlv.carolocup.build/code-prefix/src/code-build/_CPack_Packages/Linux/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/opt/opendlv.carolocup.build/code-prefix/src/code-build/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post



%postun


%pre


%preun


%files
%defattr(-,root,root,-)
"/usr/bin/carolocup-control-example"
"/usr/bin/opendlv-core-system-proxy-camera"
%dir "/usr/include/copplar-control-example"
"/usr/include/copplar-control-example/Example.h"
"/usr/lib/libcarolocup-control-example-static.a"
"/usr/lib/libopendlv-core-system-proxy-camera-static.a"
%dir "/usr/man"
%dir "/usr/man/man1"
"/usr/man/man1/carolocup-control-example.1*"
"/usr/man/man1/opendlv-core-system-proxy-camera.1*"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 0.0.2-1
  Generated by CPack RPM (no Changelog file were provided)
