# ODVDCaroloCupDataModel - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find ODVDCaroloCupDataModel library.
# The user can specify an additional search path using the CMake variable
# ODVDCAROLOCUPDATAMODEL_DIR
# First, search at the specific user path setting.
IF(NOT ("${ODVDCAROLOCUPDATAMODEL_DIR}" STREQUAL ""))
    FIND_PATH(ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR odvdcarolocupdatamodel/GeneratedHeaders_ODVDCaroloCupDataModel.h
                 NAMES odvdcarolocupdatamodel
                 PATHS ${ODVDCAROLOCUPDATAMODEL_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(ODVDCAROLOCUPDATAMODEL_LIBRARY
                 NAMES odvdcarolocupdatamodel odvdcarolocupdatamodel-static
                 PATHS ${ODVDCAROLOCUPDATAMODEL_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR}" STREQUAL "ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR-NOTFOUND")
   OR ("${ODVDCAROLOCUPDATAMODEL_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find ODVDCaroloCupDataModel in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR odvdcarolocupdatamodel/GeneratedHeaders_ODVDCaroloCupDataModel.h
                 NAMES odvdcarolocupdatamodel
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(ODVDCAROLOCUPDATAMODEL_LIBRARY
                 NAMES odvdcarolocupdatamodel odvdcarolocupdatamodel-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find ODVDCaroloCupDataModel library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(ODVDCAROLOCUPDATAMODEL_LIBRARIES ${ODVDCAROLOCUPDATAMODEL_LIBRARY})
SET(ODVDCAROLOCUPDATAMODEL_INCLUDE_DIRS ${ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibODVDCaroloCupDataModel DEFAULT_MSG
                                  ODVDCAROLOCUPDATAMODEL_LIBRARY ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR)
MARK_AS_ADVANCED(ODVDCAROLOCUPDATAMODEL_INCLUDE_DIR ODVDCAROLOCUPDATAMODEL_LIBRARY)
