version: '2'
# Please note that docker-compose does not prescribe a startup order

services:
    #odsupercomponent
    odsupercomponent:
        build: .
        network_mode: "host"
        ipc : host
        restart: on-failure
        privileged: true
        volumes:
            - ./config:/opt/configuration
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --configuration=/opt/configuration/configuration --freq=20"
        
    #odcockpit
    odcockpit:
        build: .
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - ./config:/opt/configuration
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./CsvData/Overtaking:/opt/Datacsv
        - ~/recordings:/opt/recordings
#        - .:/opt/opendlv.data
        ipc: host
       # user: odv
        depends_on:
            - odsupercomponent
        restart: on-failure
        privileged: true
        command: "/opt/od4/bin/odcockpit --cid=${CID} --configuration=/opt/configuration/configuration --freq=20"
        

        

