.\" Manpage for opendlv-core-proxy-camera
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH opendlv-core-proxy-camera 1 "21 September 2016" "0.1.0" "opendlv-core-proxy-camera man page"

.SH NAME
opendlv-core-proxy-camera \- This tool interfaces with the FH16 truck.



.SH SYNOPSIS
.B opendlv-core-proxy-camera --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-core-proxy-camera --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

