version: '2'
# Please note that docker-compose does not prescribe a startup order

services:
    #odsupercomponent
    odsupercomponent:
        build: .
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
        
    #odcockpit
    odcockpit:
        build: .
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/recordings:/opt/recordings
#        - .:/opt/opendlv.data
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"
        

        

