/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_ODVDCAROLOCUPDATAMODEL_H
#define GENERATEDHEADERS_ODVDCAROLOCUPDATAMODEL_H

#include "odvdcarolocupdatamodel/generated/chalmersrevere/carolocup/ExampleMessage.h"

#endif //GENERATEDHEADERS_ODVDCAROLOCUPDATAMODEL_H
