# -*- rpm-spec -*-
BuildRoot:      /opt/opendlv.carolocup.build/libodvdcarolocupdatamodel-prefix/src/libodvdcarolocupdatamodel-build/_CPack_Packages/Linux/RPM/libodvdcarolocupdatamodel_1.0.0_x86_64
Summary:        This is a libodvdcarolocupdatamodel, a library containing data structures for distributed software systems realized with OpenDaVINCI.
Name:           libodvdcarolocupdatamodel
Version:        1.0.0
Release:        1
License:        LGPL
Group:          unknown
Vendor:         First name Last name






Provides: libodvdcarolocupdatamodel.so()(64bit)






Prefix: /usr


%define _rpmdir /opt/opendlv.carolocup.build/libodvdcarolocupdatamodel-prefix/src/libodvdcarolocupdatamodel-build/_CPack_Packages/Linux/RPM
%define _rpmfilename libodvdcarolocupdatamodel_1.0.0_x86_64.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /opt/opendlv.carolocup.build/libodvdcarolocupdatamodel-prefix/src/libodvdcarolocupdatamodel-build/_CPack_Packages/Linux/RPM




%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/opt/opendlv.carolocup.build/libodvdcarolocupdatamodel-prefix/src/libodvdcarolocupdatamodel-build/_CPack_Packages/Linux/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/opt/opendlv.carolocup.build/libodvdcarolocupdatamodel-prefix/src/libodvdcarolocupdatamodel-build/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post



%postun


%pre


%preun


%files
%defattr(-,root,root,-)
%dir "/usr/include/odvdcarolocupdatamodel"
"/usr/include/odvdcarolocupdatamodel/GeneratedHeaders_ODVDCaroloCupDataModel.h"
"/usr/include/odvdcarolocupdatamodel/GeneratedHeaders_ODVDCaroloCupDataModel_Helper.h"
%dir "/usr/include/odvdcarolocupdatamodel/generated"
%dir "/usr/include/odvdcarolocupdatamodel/generated/chalmersrevere"
%dir "/usr/include/odvdcarolocupdatamodel/generated/chalmersrevere/carolocup"
"/usr/include/odvdcarolocupdatamodel/generated/chalmersrevere/carolocup/ExampleMessage.h"
"/usr/lib/libodvdcarolocupdatamodel-static.a"
"/usr/lib/libodvdcarolocupdatamodel.so"
%dir "/usr/share/cmake-2.8"
%dir "/usr/share/cmake-2.8/Modules"
"/usr/share/cmake-2.8/Modules/FindODVDCaroloCupDataModel.cmake"
%dir "/usr/share/cmake-3.0"
%dir "/usr/share/cmake-3.0/Modules"
"/usr/share/cmake-3.0/Modules/FindODVDCaroloCupDataModel.cmake"
%dir "/usr/share/cmake-3.5"
%dir "/usr/share/cmake-3.5/Modules"
"/usr/share/cmake-3.5/Modules/FindODVDCaroloCupDataModel.cmake"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0.0-1
  Generated by CPack RPM (no Changelog file were provided)
